# Generated by Django 5.2.4 on 2025-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('follow', 'started following you'), ('comment_like', 'liked your comment')], max_length=50),
        ),
    ]
